version: "2"

services:

  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./html/src:/var/www/html
      
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: development_db
    volumes:
      - ./mysql:/var/lib/mysql